### ISSUE TITLE
hash table implementation updated, new functional programming suite

### ISSUE THREAD

**Issue by Shambles-Dev** [rshipp/ahk-libs#7]
I am not very knowledgeable about Github.  I do not know how these links to projects work, but when I follow the one here it shows a version of my hash table library from long ago.  It has been updated since then (hash tables can now be constructed from arrays, I added better error reporting).  https://github.com/Shambles-Dev/AutoHotkey-HashTable

I have also been working on this https://github.com/Shambles-Dev/AutoHotkey-Facade  I still need to implement much more thorough error handling.  Even if it is not suitable to link to, I would be interested in your feedback.  It is essentially a much more complete version of my old Composer library without the dependency on Plaster that made me have to abandon it.

**Comment by rshipp** [comment]
Hi, thanks for the issue. I've added Facade and updated everything else. I'm afraid I can't give any feedback, I haven't used ahk in years. 

I'm going to archive this repo, since its a pain to maintain and I haven't updated it in a while. You might want to add your projects to the [Awesome AutoHotkey](https://github.com/ahkscript/awesome-AutoHotkey) list, if you haven't already.
